site_name: NovaCord
site_url: https://atpascal07.github.io/NovaCord/
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    primary: indigo
    accent: blue
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Features: features.md
  - Examples: examples.md
  - Contributing: contributing.md
  - Changelog: changelog.md
